global:
  resolve_timeout: 5m

route:
  receiver: "pager"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: "pager"
    # example: add email or slack webhook here. For demo use webhook to display in UI
    webhook_configs:
      - url: "http://webhook.site/your-temp-url" # replace with real webhook in production
